// This file is generated automatically by scripts/build-data.mjs
// Do not edit this file manually!

import { LanguageData, Sentence } from './types';

export const languageData: LanguageData = {
  "comer": {
    "presente": [
      {
        "template": "Yo ______ (comer) paella todos los domingos.",
        "answer": "como"
      },
      {
        "template": "Tú ______ (comer) muchas frutas.",
        "answer": "comes"
      },
      {
        "template": "Él ______ (comer) en el restaurante nuevo.",
        "answer": "come"
      },
      {
        "template": "Nosotros ______ (comer) juntos.",
        "answer": "comemos"
      },
      {
        "template": "Vosotros ______ (comer) muy rápido.",
        "answer": "coméis"
      },
      {
        "template": "Ellos ______ (comer) pescado.",
        "answer": "comen"
      }
    ],
    "pretérito": [
      {
        "template": "Ayer, yo ______ (comer) tacos.",
        "answer": "comí"
      },
      {
        "template": "Anoche, tú ______ (comer) pizza.",
        "answer": "comiste"
      },
      {
        "template": "La semana pasada, ella ______ (comer) ensalada.",
        "answer": "comió"
      },
      {
        "template": "Nosotros ______ (comer) en casa ayer.",
        "answer": "comimos"
      },
      {
        "template": "Vosotros ______ (comer) tarde.",
        "answer": "comisteis"
      },
      {
        "template": "Ellos ______ (comer) mucho en la fiesta.",
        "answer": "comieron"
      }
    ]
  },
  "hablar": {
    "futuro": [
      {
        "template": "Mañana, yo ______ (hablar) con el profesor.",
        "answer": "hablaré"
      },
      {
        "template": "La próxima semana, tú ______ (hablar) en la conferencia.",
        "answer": "hablarás"
      },
      {
        "template": "Él ______ (hablar) con sus padres luego.",
        "answer": "hablará"
      },
      {
        "template": "Nosotros ______ (hablar) más tarde.",
        "answer": "hablaremos"
      },
      {
        "template": "Vosotros ______ (hablar) con el director.",
        "answer": "hablaréis"
      },
      {
        "template": "Ellos ______ (hablar) sobre sus planes.",
        "answer": "hablarán"
      }
    ],
    "presente": [
      {
        "template": "Yo ______ (hablar) español.",
        "answer": "hablo"
      },
      {
        "template": "Tú ______ (hablar) inglés muy bien.",
        "answer": "hablas"
      },
      {
        "template": "Ella ______ (hablar) con su amiga.",
        "answer": "habla"
      },
      {
        "template": "Nosotros ______ (hablar) sobre el proyecto.",
        "answer": "hablamos"
      },
      {
        "template": "Vosotros ______ (hablar) demasiado.",
        "answer": "habláis"
      },
      {
        "template": "Ellos ______ (hablar) por teléfono.",
        "answer": "hablan"
      }
    ]
  }
};

export const availableVerbs: string[] = [
  "comer",
  "hablar"
];

export const availableTenses: string[] = [
  "futuro",
  "presente",
  "pretérito"
];

// Groupings based on actual available tenses
export const tenseGroups: { [key: string]: string[] } = {
  "present": [
    "presente"
  ],
  "past": [
    "pretérito"
  ],
  "future": [
    "futuro"
  ]
};

// Helper function to get sentences for selection
export function getSelectedSentences(selectedVerbs: Set<string>, selectedTenses: Set<string>): Sentence[] {
  const sentences: Sentence[] = [];
  selectedVerbs.forEach(verb => {
    if (languageData[verb]) {
      selectedTenses.forEach(tense => {
        if (languageData[verb][tense]) {
          // Add verb/tense info to each sentence for potential future use
          const sentencesWithMeta = languageData[verb][tense].map(s => ({
              ...s,
              verb,
              tense
          }));
          sentences.push(...sentencesWithMeta);
        }
      });
    }
  });
  // Simple shuffle
  return sentences.sort(() => Math.random() - 0.5);
}
